# permissions for end users to view tlqclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tlqcluster-viewer-role
rules:
- apiGroups:
  - tlq.tongtech.com
  resources:
  - tlqclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tlq.tongtech.com
  resources:
  - tlqclusters/status
  verbs:
  - get
