# permissions for end users to view tlqmasters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tlqmaster-viewer-role
rules:
- apiGroups:
  - tlq.tongtech.com
  resources:
  - tlqmasters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tlq.tongtech.com
  resources:
  - tlqmasters/status
  verbs:
  - get
