# permissions for end users to view tlqworkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tlqworker-viewer-role
rules:
- apiGroups:
  - tlq.tongtech.com
  resources:
  - tlqworkers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tlq.tongtech.com
  resources:
  - tlqworkers/status
  verbs:
  - get
