# permissions for end users to edit tlqworkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tlqworker-editor-role
rules:
- apiGroups:
  - tlq.tongtech.com
  resources:
  - tlqworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tlq.tongtech.com
  resources:
  - tlqworkers/status
  verbs:
  - get
